project:
  type: website

website:
  title: "MATH 341 Differential Equations"
  navbar:
    left:
      - href: index.qmd
        text: "Syllabus"
      - text: "Notes"
        href: notes.qmd
      - text: "Examples"
        href: examples.qmd
      - text: "Additional Topics"
        href: topics.qmd
      - text: "Python Reference"
        href: py_tutorial.qmd
  sidebar:
    - title: "Notes"
      style: "docked"
      background: light
      contents:
        - notes.qmd
        - notes_01.qmd
        - notes_02.qmd
        - notes_03.qmd
    - title: "Examples"
      style: "docked"
      background: light
      contents:
        - examples.qmd
        - examples_01.qmd
        - examples_02.qmd
    - title: "Additional Topics"
      style: "docked"
      background: light
      contents:
        - topics.qmd
        - topics_01.qmd
        - topics_02.qmd
        - topics_03.qmd
        - topics_04.qmd
    
format:
  html:
    theme: 
      light: pulse
      dark: cyborg
    css: styles.css
    toc: true



