---
title: "Worked Examples"
jupyter: diffeq_py
license: "CC BY-NC-SA 4.0"
bibliography: diffeq_bib.bib
---

This page is a compendium of fully worked examples for MATH 341 *Differential Equations* during the Fall 2026 semester. Sections will be added and edited as the course progresses. The examples linked here are not meant to substitute for those in the course textbook (@logan2015first). They are also not meant to be a substitute for attending lectures.

- [Showing a function is a solution](https://math341diffeq.netlify.app/examples_01) works through the details of showing that a particular function solves a particular differential equation. 

- [First-order equations](https://math341diffeq.netlify.app/examples_02) worked examples for first-order equations including topics such as sketching slope-fields, finding general solutions and solutions to initial value problems for separable and linear equations, integrating factors, and applications to mechanics, population biology, and electric circuits.

- [Second-order linear constant coefficient equations](https://math341diffeq.netlify.app/examples_03) provides worked examples for second-order linear equations with constant coefficients including topics such as homogeneous equations, nonhomogeneous equations and undetermined coefficients. Initial value problems and applications are also considered. 

- [Variation of parameters](https://math341diffeq.netlify.app/examples_04) provides worked examples solving second-order linear equations with non-constant coefficients using the method of variation of parameters. Initial value problems and applications are also considered. 

- [Laplace transforms](https://math341diffeq.netlify.app/examples_05) provides worked examples computing Laplace transforms and inverse transforms.

- [More on Laplace transforms](https://math341diffeq.netlify.app/examples_06) provides worked examples related to using Laplace transforms to solve ODEs, the convolution property, and impulse forces.

- [Matrices and linear algebra](https://math341diffeq.netlify.app/examples_07) provides worked examples related to using matrices and linear algebra including eigenvalues.

