---
title: "Notes"
jupyter: diffeq_py
license: "CC BY-NC-SA 4.0"
bibliography: diffeq_bib.bib
---

This page contains the notes (by topic not necessarily by lecture) for MATH 341 *Differential Equations* during the Fall 2026 semester. Sections will be added and edited as the course progresses. The notes are not meant to be a substitute for the textbook (@logan2015first), but rather a supplement to it. They are also not meant to be a substitute for attending lectures. Students are encouraged to read through the relevant section of notes prior to attending lectures.

- [Section 1](https://math341diffeq.netlify.app/notes_01) (~75-90 minutes lecture time) introduces the basic idea of a differential equation with an emphasis on ordinary differential equations (ODEs). 

- [Section 2](https://math341diffeq.netlify.app/notes_02) (~120–140 minutes lecture time) covers first-order ODEs including slope-fields, separable equations, linear equations, integrating factors, and applications.

- [Section 3](https://math341diffeq.netlify.app/notes_03) (~120–145 minutes lecture time) covers one-dimensional dynamical system including topics such as equilibrium points, stability, phase-line, and bifurcations.

- [Section 4](https://math341diffeq.netlify.app/notes_04) (~125–160 minutes lecture time) covers second-order linear constant-coefficient ODEs and applications.

- [Section 5](https://math341diffeq.netlify.app/notes_05) (~100–120 minutes lecture time) covers the method of [variation of parameters](https://en.wikipedia.org/wiki/Variation_of_parameters) for second-order linear ODEs that do not necessarily have constant coefficients.

- [Section 6](https://math341diffeq.netlify.app/notes_06) (~125–145 minutes lecture time) covers the definition and basic properties of [Laplace Transforms](https://en.wikipedia.org/wiki/Laplace_transform).

- [Section 7](https://math341diffeq.netlify.app/notes_07) (~120–140 minutes lecture time) covers the application of [Laplace Transforms](https://en.wikipedia.org/wiki/Laplace_transform) to solve ODEs.

- [Section 8](https://math341diffeq.netlify.app/notes_08) (~125–145 minutes lecture time) covers the convolution property of [Laplace Transforms](https://en.wikipedia.org/wiki/Laplace_transform) and impulse forces.

- [Section 9](https://math341diffeq.netlify.app/notes_09) (~125–145 minutes lecture time) covers systems of first-order linear ODEs and applications. Includes a discussion of matrices. 

- [Section 10](https://math341diffeq.netlify.app/notes_10) (~125–145 minutes lecture time) covers the eigenvalue problem for linear systems of ODEs and applications for solving linear systems.

- [Section 11](https://math341diffeq.netlify.app/notes_11) (~120–140 minutes lecture time) covers phase plane analysis for linear systems of ODEs, nonhomogeneous linear systems, and applications.

- [Section 12](https://math341diffeq.netlify.app/notes_12) (~125–145 minutes lecture time) introduces phase plane analysis for nonlinear systems of ODEs.

- [Section 13](https://math341diffeq.netlify.app/notes_13) (~120–140 minutes lecture time) introduces applications of phase plane analysis for nonlinear systems of ODEs.

- [Section 14](https://math341diffeq.netlify.app/notes_14) (~120–140 minutes lecture time) introduces numerical methods and computation of solutions for initial value problems for ODEs.


